// Package factory implements the Factory Mode (F5) — a warehouse/factory
// logistics simulation with 1000-2000 autonomous mobile robots (AMRs).
package factory

import (
	"math/rand"
	"swarmsim/domain/physics"
	"swarmsim/domain/swarm"
)

// World dimensions
const (
	WorldW = 3000.0 // total world width
	WorldH = 2000.0 // total world height

	// Yard area (top section — truck road, loading docks)
	YardH = 600.0 // yard height (Y: 0 to 600)

	// Hall area (lower section — production)
	HallX      = 200.0  // left wall X
	HallY      = YardH  // top of hall (Y=600)
	HallW      = 2600.0 // inner hall width
	HallH      = 1300.0 // inner hall height
	WallThick  = 10.0   // wall thickness

	// Bot rendering
	FactoryBotRadius = 3.0  // small bots for factory view
	FactoryBotSpeed  = 3.0  // pixels per tick (fast for large factory)
	DefaultBotCount  = 1000

	// Road
	RoadY = 250.0 // center of truck road
	RoadH = 80.0  // road width

	// Maintenance schedule thresholds
	MaintenanceWarningHours  = 20000
	MaintenanceMandatoryHours = 30000
	PreventiveRepairTime     = 100 // ticks (vs 200 for breakdown)

	// Order system
	OrderSpawnInterval = 1000 // ticks between new orders
	OrderMinQty        = 3
	OrderMaxQty        = 8
	OrderDeadlineTicks = 8000 // ticks to complete an order

	// Alert system
	MaxVisibleAlerts = 5
	AlertFadeTicks   = 300
)

// BotRole identifies the specialization of a factory bot.
type BotRole int

const (
	RoleTransporter BotRole = iota // standard — moves parts between zones
	RoleForklift                    // heavy lifter — carries 2 parts at once, slower
	RoleExpress                     // fast courier — 2x speed, less energy capacity
)

// CustomerOrder represents a customer order that must be fulfilled.
type CustomerOrder struct {
	ID          int
	OutputColor int
	Quantity    int
	Fulfilled   int
	Deadline    int  // tick by which it should be done
	Completed   bool
}

// FactoryAlert represents a real-time event notification.
type FactoryAlert struct {
	Message string
	Tick    int
	Color   [3]uint8
}

// TaskType identifies a factory task.
type TaskType int

const (
	TaskNone TaskType = iota
	TaskUnloadTruck
	TaskTransportToMachine
	TaskTransportFromMachine
	TaskLoadTruck
	TaskGoCharge
	TaskGoRepair
	TaskReturnDefect  // return defective part to inbound storage
	TaskIncomingQC    // incoming QC inspection: move part from QC area to inbound storage
)

// Task represents a single job for a robot. Tasks are generated by the
// Kanban pull system (GenerateTasks) and assigned to idle bots. Each task
// describes a pickup location, a delivery location, and what part to move.
type Task struct {
	Type     TaskType // what kind of work this task represents
	SourceX  float64  // X coordinate of the pickup location
	SourceY  float64  // Y coordinate of the pickup location
	DestX    float64  // X coordinate of the delivery destination
	DestY    float64  // Y coordinate of the delivery destination
	Priority int      // scheduling weight; higher = more urgent (e.g. 100 for charging)
	Assigned int      // bot index currently executing this task (-1 = unassigned)
	PartColor int     // color code of the part being moved (1=red, 2=blue, 3=yellow, 4=green, 5=defective)
	RecipeStep int    // current step index within the production recipe (0-based)
	PartRecipe int    // index into FactoryState.Recipes for multi-step tracking (-1 = none)
}

// TaskQueue manages pending factory tasks.
type TaskQueue struct {
	Tasks []Task
}

// Machine represents an assembly or processing machine on the production floor.
// Machines accept parts of a specific InputColor and, after ProcessTime ticks,
// produce a part of OutputColor. They can overheat if run continuously and
// consume energy from the factory budget while active.
type Machine struct {
	// Position and dimensions in world coordinates
	X, Y float64 // top-left corner position
	W, H float64 // width and height of the machine footprint

	// Production configuration
	InputColor  int // required input part color (1=red, 2=blue, 3=yellow, 4=green)
	OutputColor int // color of the produced output part
	MaxInput    int // maximum number of parts that can be queued for processing
	ProcessTime int // total ticks needed to process one input into one output

	// Runtime production state
	CurrentInput int  // number of parts currently queued in the input buffer
	ProcessTimer int  // ticks remaining until current item is finished
	OutputReady  bool // true when a finished product is waiting for collection
	Active       bool // true when the machine is actively processing an input
	NeedsInput   bool // Kanban pull flag: set true when machine has capacity and requests material

	// Thermal management (Feature 4)
	Temperature float64 // current heat level (0-100); rises while active, decays while idle
	CoolingDown bool    // true when machine is paused for mandatory cool-down

	// Energy economics (Feature 7b)
	PowerCostPerTick float64 // energy cost deducted from Budget each active tick (default 0.02)
}

// ChargingStation is a fixed location where bots recharge their energy.
// Multiple bots can charge simultaneously up to MaxBots capacity.
// Charging costs vary by time of day (see EnergyCostDay/EnergyCostNight).
type ChargingStation struct {
	X, Y       float64 // top-left corner position in world coordinates
	W, H       float64 // width and height of the station footprint
	MaxBots    int     // maximum number of bots that can charge simultaneously
	ChargeRate float64 // energy units restored per tick per bot
	Occupants  []int   // indices of bots currently docked and charging
}

// RepairWorkshop fixes malfunctioning bots.
type RepairWorkshop struct {
	X, Y        float64
	W, H        float64
	RepairTime  int // ticks to repair
	CurrentBot  int // bot being repaired (-1 = empty)
	RepairTimer int // ticks remaining
}

// LoadingDock is where trucks park for loading/unloading.
type LoadingDock struct {
	X, Y     float64
	W, H     float64
	IsInbound bool   // true=receiving, false=shipping
	TruckIdx int     // index of parked truck (-1 = empty)
}

// StorageSlot represents a single shelf slot in a storage area (for FIFO).
type StorageSlot struct {
	PartColor int
	Tick      int // when stored (for FIFO ordering)
}

// StorageArea buffers parts between stages.
type StorageArea struct {
	X, Y     float64
	W, H     float64
	Parts    []int // part colors stored (legacy, kept for compat)
	MaxParts int
	Slots    []StorageSlot // FIFO storage slots
}

// Door connects hall and yard.
type Door struct {
	X, Y       float64
	W          float64 // opening width
	Open       bool
	CloseTimer int // auto-close countdown (0 = indefinite)
}

// FactoryTruck drives across the yard.
type FactoryTruck struct {
	X, Y      float64
	W, H      float64
	Speed     float64
	Direction int // 0=moving right (inbound), 1=moving left (outbound)
	Phase     TruckPhase
	DockIdx   int // which dock (-1 = driving)
	Parts     []int // part colors carried
	MaxParts  int
	Counter   int // general-purpose counter (e.g. loading timeout)
	MoveTick  int // ticks since truck started moving (for exhaust acceleration)
}

// TruckPhase describes the truck lifecycle.
type TruckPhase int

const (
	TruckEntering TruckPhase = iota
	TruckParked
	TruckUnloading
	TruckLoading
	TruckExiting
	TruckWaiting // off-screen, waiting for next arrival
)

// WeatherType describes current weather in the yard.
type WeatherType int

const (
	WeatherClear WeatherType = 0
	WeatherRain  WeatherType = 1
)

// SparkEffect is a brief spark burst when a malfunction occurs.
type SparkEffect struct {
	X, Y    float64
	Tick    int
	VX, VY  [4]float64 // 4 spark velocities
}

// MachineFinishEffect is a big pulse ring when a machine completes processing.
type MachineFinishEffect struct {
	X, Y float64
	Tick int
}

// TruckArriveFlash is a screen-edge flash when a truck arrives.
type TruckArriveFlash struct {
	Tick int // ticks since flash started
}

// ProductionRecipe defines a multi-step production sequence through machines.
type ProductionRecipe struct {
	Steps      []int // machine indices in order, e.g. [0, 2, 5]
	InputColor int   // which part color triggers this recipe
}

// FactoryState holds the complete simulation state for Factory Mode (F5).
// It models a warehouse/factory with 1000-2000 autonomous mobile robots (AMRs)
// that transport parts between loading docks, storage areas, and machines.
type FactoryState struct {
	// Core robot fleet
	Bots     []swarm.SwarmBot // all factory robots (positions, energy, state)
	BotCount int              // configured bot count (may differ from len(Bots) during transitions)

	// Production infrastructure
	Machines []Machine         // assembly/processing machines on the production floor
	Chargers []ChargingStation // energy recharge stations distributed across the hall
	Workshop RepairWorkshop    // single repair workshop for malfunctioning bots
	Docks    []LoadingDock     // truck loading/unloading bays in the yard
	Doors    []Door            // gates connecting the yard and hall areas
	Walls    []*physics.Obstacle // static wall segments for collision detection
	Storage  []StorageArea     // buffer areas between stages (indexed by named indices below)
	Trucks   []FactoryTruck    // active trucks in the yard (entering, docked, or exiting)

	// Named storage zone indices (set during layout build by buildLayout)
	InboundStorageIdx  int // index into Storage for the receiving/inbound buffer
	QCStorageIdx       int // index into Storage for the quality control inspection area
	OutboundStorageIdx int // index into Storage for the outbound/shipping buffer
	Tasks              TaskQueue // pending and assigned work items for robots

	// Per-bot factory state (parallel slices, indexed by bot index)
	Malfunctioning []bool    // true = bot has a malfunction and operates at reduced capacity
	RepairQueue    []int     // bot indices queued and waiting for workshop availability
	BotRoles       []BotRole // role specialization per bot (Transporter/Forklift/Express)
	BotOpHours     []int     // cumulative operating hours since last maintenance (ticks)
	BotDeliveries  []int     // lifetime delivery count per bot (drives experience speed bonus)

	// Traffic rules: per-bot honk flash countdown
	HonkFlash []int

	// Queue buffers: per-bot wait counter at machines
	BotCounters []int

	// Multi-step production recipes
	Recipes []ProductionRecipe

	// Pallet transport: per-bot slice of part colors being carried (forklifts only)
	BotPallet [][]int

	// Parking zones (center positions)
	ParkingZones [][2]float64

	// Pre-computed parking slot assignments (one per bot, computed once per tick)
	BotParkingSlot []ParkingAssignment

	// Order system
	Orders         []CustomerOrder
	CompletedOrders int
	Score          int
	NextOrderID    int
	OrderTimer     int // ticks until next order

	// Alert system
	Alerts []FactoryAlert

	// Clipboard flash (for stats export)
	ClipboardFlash int

	// Truck spawning
	TruckTimer int // ticks until next inbound truck

	// Spatial indexing
	BotHash *physics.SpatialHash
	ObsHash *physics.SpatialHash // spatial hash for static obstacles (walls)

	// Camera
	CamX, CamY float64
	CamZoom    float64

	// Simulation
	Tick       int
	Paused     bool
	Speed      float64
	Rng        *rand.Rand
	SelectedBot   int // -1 = none
	FollowCamBot  int // -1 = off; when >= 0 camera follows this bot
	HoverBot      int // -1 = none; bot index under cursor (for tooltip)

	// Particle / FX state
	ExhaustParticles []ExhaustParticle     // truck exhaust particles
	PulseEffects     []PulseEffect         // pickup/delivery pulse rings
	SparkEffects     []SparkEffect         // malfunction sparks
	MachineFinishFX  []MachineFinishEffect // machine completion big pulses
	TruckArriveFlash TruckArriveFlash      // screen-edge flash on truck arrival

	// Weather system
	Weather      WeatherType
	WeatherTimer int // ticks until next weather change

	// Help overlay
	ShowHelp     bool

	// Heatmap overlay
	ShowHeatmap  bool
	HeatmapGrid  []int // 60x40 = 2400 cells
	HeatmapW     int   // grid width (60)
	HeatmapH     int   // grid height (40)

	// Selected bot path trail
	SelectedBotPath    [][2]float64
	SelectedBotPathIdx int // ring buffer write index

	// Throughput tracking for dashboard
	ThroughputHistory   []int // ring buffer, last 100 samples
	ThroughputIdx       int   // write index
	ThroughputAccum     int   // parts processed since last sample
	ThroughputSampleTick int  // last sample tick
	LastPartsProcessed  int   // snapshot for delta calculation

	// Shift system
	ShiftTimer   int    // ticks until next shift change
	ShiftOnDuty  []bool // per-bot: true = on shift (working)

	// Emergency system
	Emergency      bool // emergency mode active
	EmergencyTimer int  // ticks remaining in emergency

	// Bot communication cooldowns (per-bot)
	ChargerBusyDelay []int // per-bot: ticks to delay charging

	// Part entry timestamps for cycle time tracking (per task)
	// We track when a part enters the system (tick of inbound unload)
	PartEntryTick map[int]int // partID -> tick entered system (simple counter-based)
	NextPartID    int

	// Efficiency sparkline (last 20 samples of working/(working+idle) ratio, 0-100)
	EfficiencyHistory [20]int
	EfficiencyIdx     int
	EfficiencySampleTick int

	// Factory achievements
	FactoryAchievements []string // unlocked achievement IDs
	AchievementPopup    string   // currently displayed achievement text
	AchievementTimer    int      // ticks remaining for popup display

	// Feature 7: Inventory Tracking
	MinStockLevel    int  // minimum parts in inbound storage before warning (default: 5)
	StockWarning     bool // true when inbound storage below min level
	OutboundFull     bool // true when outbound storage is near capacity

	// Feature 9: Energy Economics
	Budget          float64 // factory budget (starts at 10000)
	EnergyCostDay   float64 // cost per energy unit during day (0.1)
	EnergyCostNight float64 // cost per energy unit during night (0.03)
	TotalEnergyCost float64 // cumulative spending on energy

	// Feature: Forklift Battery Swap
	BatterySwapTimer []int // per-bot countdown (30 ticks) for forklift battery swap at workshop

	// Feature: Material Costs + Revenue
	MaterialCostPerPart float64 // cost per incoming raw part (default 50)
	RevenuePerProduct   float64 // revenue per completed product shipped (default 200)
	TotalMaterialCost   float64 // cumulative material cost
	TotalRevenue        float64 // cumulative revenue

	// Feature 10: Maintenance Planner
	ShowMaintPlanner bool // toggled with P key

	// Feature 6: QC rejection flash effects
	QCRejectEffects []QCRejectEffect

	// Feature 11: Random events system
	ActiveEvent FactoryEvent
	EventTimer  int // ticks until next event
	// Feature 11: Machine breakdown target (machine index disabled by event)
	EventBreakdownMachine int // -1 = none

	// Stats
	Stats FactoryStats

	// Factory tutorial (guided tour for new users)
	FactoryTutorial *FactoryTutorial
	ShowFactoryTut  bool // true on first factory mode entry
}

// FactoryTutorial tracks the 10-step guided factory tour.
type FactoryTutorial struct {
	Active bool
	Step   int
	Timer  int // auto-advance timer (ticks)
}

// QCRejectEffect is a brief red X flash at QC area when part rejected.
type QCRejectEffect struct {
	X, Y float64
	Tick int
}

// FactoryEvent represents a random event that affects factory operations.
type FactoryEvent struct {
	Type   int
	Timer  int  // ticks remaining
	Active bool
}

// ExhaustParticle is a small gray dot trailing behind moving trucks.
type ExhaustParticle struct {
	X, Y   float64
	Life   int // ticks remaining
	Alpha  uint8
	Size   float64 // base radius (0 = default 2.0)
	DriftY float64 // vertical drift per tick (negative = upward)
}

// PulseEffect is a brief expanding ring when a bot picks up or delivers.
type PulseEffect struct {
	X, Y  float64
	Tick  int // ticks since spawned
	MaxR  float64
	Color [3]uint8
}

// ParkingAssignment maps a bot to its parking zone and grid slot.
// Computed once per tick by PrecomputeParkingSlots, used by botWander for O(1) lookup.
type ParkingAssignment struct {
	ZoneIdx int
	SlotIdx int // grid position within zone
}

// PrecomputeParkingSlots iterates all idle bots once and assigns each to the
// nearest parking zone with a grid slot index. This replaces the O(n*idle_bots)
// inner loop that was previously inside botWander.
func PrecomputeParkingSlots(fs *FactoryState) {
	// Grow or reset the per-bot slice
	for len(fs.BotParkingSlot) < len(fs.Bots) {
		fs.BotParkingSlot = append(fs.BotParkingSlot, ParkingAssignment{})
	}
	if len(fs.BotParkingSlot) > len(fs.Bots) {
		fs.BotParkingSlot = fs.BotParkingSlot[:len(fs.Bots)]
	}

	if len(fs.ParkingZones) == 0 {
		return
	}

	// Count how many idle bots are assigned to each zone
	zoneCounts := make([]int, len(fs.ParkingZones))

	for i := range fs.Bots {
		bot := &fs.Bots[i]
		// Only compute for idle, on-shift bots (same condition as botWander callers)
		isIdle := bot.State == BotIdle
		onShift := i < len(fs.ShiftOnDuty) && fs.ShiftOnDuty[i]
		if !isIdle || !onShift {
			fs.BotParkingSlot[i] = ParkingAssignment{ZoneIdx: 0, SlotIdx: 0}
			continue
		}

		// Find nearest parking zone
		bestZoneIdx := 0
		bestDist := 1e18
		for zi, pz := range fs.ParkingZones {
			dx := pz[0] - bot.X
			dy := pz[1] - bot.Y
			d := dx*dx + dy*dy
			if d < bestDist {
				bestDist = d
				bestZoneIdx = zi
			}
		}

		fs.BotParkingSlot[i] = ParkingAssignment{
			ZoneIdx: bestZoneIdx,
			SlotIdx: zoneCounts[bestZoneIdx],
		}
		zoneCounts[bestZoneIdx]++
	}
}

// FindBotTask returns the task index assigned to the given bot, or -1.
func FindBotTask(fs *FactoryState, botIdx int) int {
	for i := range fs.Tasks.Tasks {
		if fs.Tasks.Tasks[i].Assigned == botIdx {
			return i
		}
	}
	return -1
}

// FactoryStats tracks real-time throughput, efficiency, and KPI metrics.
// Updated each tick by UpdateStats and displayed on the factory dashboard.
type FactoryStats struct {
	// Throughput counters (cumulative, never reset)
	PartsProcessed int // total parts picked up and delivered by bots
	TrucksUnloaded int // inbound trucks fully unloaded
	TrucksLoaded   int // outbound trucks fully loaded and dispatched

	// Real-time bot status snapshot (recomputed each tick)
	BotsCharging  int // bots currently docked at a charging station
	BotsRepairing int // bots currently at the repair workshop
	BotsIdle      int // bots with no task, wandering or parked
	BotsWorking   int // bots actively executing a task (moving to source/dest)
	BotsOffShift  int // bots in off-duty state (not available for work)

	// Delivery performance
	AvgDeliveryTime float64    // rolling average ticks per delivery
	MachineUtil     [4]float64 // per-machine utilization ratio (0.0-1.0), first 4 machines

	// KPI tracking (cumulative)
	MachineUptime   [6]int // total ticks each of the 6 machines spent actively processing
	TotalCycleTime  int    // sum of all individual part cycle times (entry to shipment)
	CompletedCycles int    // parts that completed the full pipeline and were shipped
	DefectCount     int    // parts flagged as defective by QC-Final inspection
	GoodParts       int    // non-defective parts produced
	TotalParts      int    // total parts produced (GoodParts + DefectCount)
	WIP             int    // work-in-progress: parts currently being transported
	IncomingRejects int    // parts rejected at incoming QC before entering production

	// Leaderboard (Feature 12)
	TopWorkers [3][2]int // top-3 most productive bots: [rank][0]=bot index, [rank][1]=delivery count
}

// NewFactoryState creates and initializes a factory world.
func NewFactoryState(botCount int) *FactoryState {
	if botCount <= 0 {
		botCount = DefaultBotCount
	}

	fs := &FactoryState{
		BotCount:    botCount,
		CamX:        WorldW / 2,
		CamY:        WorldH / 2,
		CamZoom:     0.5,
		Speed:       1.0,
		Rng:         rand.New(rand.NewSource(42)),
		SelectedBot:  -1,
		FollowCamBot: -1,
		HoverBot:     -1,

		// Weather
		Weather:      WeatherClear,
		WeatherTimer: 5000,

		// Heatmap
		HeatmapW: 60,
		HeatmapH: 40,
		HeatmapGrid: make([]int, 60*40),

		// Throughput
		ThroughputHistory: make([]int, 100),

		// Selected bot path
		SelectedBotPath: make([][2]float64, 100),
	}

	// Build layout
	fs.buildLayout()

	// Build spatial hash for wall obstacles (fast collision lookup)
	fs.ObsHash = physics.NewSpatialHash(WorldW, WorldH, 100)
	for i, wall := range fs.Walls {
		cx := wall.X + wall.W/2
		cy := wall.Y + wall.H/2
		fs.ObsHash.Insert(i, cx, cy)
	}

	// Spawn bots inside the hall
	fs.Bots = make([]swarm.SwarmBot, botCount)
	for i := range fs.Bots {
		fs.Bots[i] = swarm.SwarmBot{
			X:      HallX + 50 + fs.Rng.Float64()*(HallW-100),
			Y:      HallY + 50 + fs.Rng.Float64()*(HallH-100),
			Speed:  FactoryBotSpeed,
			Angle:  fs.Rng.Float64() * 6.283,
			Energy: 100,
			CarryingPkg: -1,
		}
	}

	// Init per-bot factory state
	fs.Malfunctioning = make([]bool, botCount)
	fs.ShiftOnDuty = make([]bool, botCount)
	fs.ChargerBusyDelay = make([]int, botCount)
	fs.BotRoles = make([]BotRole, botCount)
	fs.BotOpHours = make([]int, botCount)
	fs.BotDeliveries = make([]int, botCount)
	fs.HonkFlash = make([]int, botCount)
	fs.BotCounters = make([]int, botCount)
	fs.BotPallet = make([][]int, botCount)
	fs.TruckTimer = 200 // first truck arrives quickly
	fs.ShiftTimer = 5000 // first shift change at 5000 ticks
	fs.PartEntryTick = make(map[int]int)
	fs.OrderTimer = 500 // first order arrives soon

	// Multi-step production recipes:
	// Recipe 0 (Red parts): CNC-1 (M0) -> Assembly (M2) -> QC-Final (M5)
	// Recipe 1 (Blue parts): CNC-2 (M1) -> Drill-1 (M3) -> QC-Final (M5)
	// Recipe 2 (Yellow parts): CNC-1 (M0) -> Drill-2 (M4) -> QC-Final (M5)
	fs.Recipes = []ProductionRecipe{
		{Steps: []int{0, 2, 5}, InputColor: 1},
		{Steps: []int{1, 3, 5}, InputColor: 2},
		{Steps: []int{0, 4, 5}, InputColor: 3},
	}

	// Initialize bot roles: 60% Transporter, 25% Forklift, 15% Express
	for i := 0; i < botCount; i++ {
		pct := float64(i) / float64(botCount)
		if pct < 0.60 {
			fs.BotRoles[i] = RoleTransporter
		} else if pct < 0.85 {
			fs.BotRoles[i] = RoleForklift
			fs.Bots[i].Speed = 2.0
			fs.Bots[i].Energy = 120
		} else {
			fs.BotRoles[i] = RoleExpress
			fs.Bots[i].Speed = 5.0
			fs.Bots[i].Energy = 60
		}
	}

	// Initialize parking zones (one in receiving area, one in shipping area)
	fs.ParkingZones = [][2]float64{
		{ZoneReceivingX + ZoneReceivingW/2, HallY + HallH - 200},
		{ZoneShippingX + ZoneShippingW/2, HallY + HallH - 200},
	}

	// Initialize shift: 70% on duty, 30% off
	for i := 0; i < botCount; i++ {
		fs.ShiftOnDuty[i] = i < botCount*7/10
	}

	// Feature 7: Inventory tracking defaults
	fs.MinStockLevel = 5

	// Feature 9: Energy economics defaults
	fs.Budget = 10000.0
	fs.EnergyCostDay = 0.1
	fs.EnergyCostNight = 0.03

	// Forklift battery swap timers
	fs.BatterySwapTimer = make([]int, botCount)

	// Material costs + revenue defaults
	fs.MaterialCostPerPart = 50.0
	fs.RevenuePerProduct = 200.0

	// Feature 11: Random events init
	fs.EventTimer = 5000 + fs.Rng.Intn(3000) // first event in 5000-8000 ticks
	fs.EventBreakdownMachine = -1

	// Init achievements
	fs.FactoryAchievements = make([]string, 0)

	// Init spatial hash
	fs.BotHash = physics.NewSpatialHash(WorldW, WorldH, 50)

	return fs
}
