package swarm

import "math"

// Harmony Search Optimization (HSO): A music-inspired metaheuristic algorithm
// that mimics the process of musicians improvising harmonies. Each musician
// (decision variable) plays a note (value) that together form a harmony
// (solution vector). The algorithm maintains a Harmony Memory (HM) of
// previously played good harmonies and generates new ones by:
//
//   Memory consideration — pick a note from the HM with probability HMCR
//   Pitch adjustment    — slightly perturb the selected note with probability PAR
//   Random selection    — choose a completely random note otherwise
//
// The new harmony replaces the worst in HM if it is better, maintaining a
// fixed-size archive of elite solutions. The simplicity and few parameters
// make HSO attractive for continuous and combinatorial optimization alike.
//
// In this 2-D swarm simulation each bot represents a harmony whose "notes"
// are its (X, Y) position. The fitness is proximity to the light source (or
// arena center). Bots steer toward target positions drawn from the HM,
// producing a visually distinct convergence pattern: an initial exploratory
// scatter that gradually coalesces into tight clusters around the optimum.
//
// Reference: Geem, Z.W., Kim, J.H., Loganathan, G.V. (2001)
//
//	"A New Heuristic Optimization Algorithm: Harmony Search",
//	SIMULATION, 76(2), pp. 60-68.

const (
	hsoSteerRate        = 0.25  // max steering change per tick (radians)
	hsoHMCR             = 0.92  // Harmony Memory Considering Rate — probability of picking from HM
	hsoPAR              = 0.45  // Pitch Adjusting Rate — probability of perturbing a HM note
	hsoBWMax            = 60.0  // initial bandwidth — maximum pitch adjustment distance (pixels)
	hsoBWMin            = 8.0   // final bandwidth — decreases over time for finer exploitation
	hsoHMSize           = 50    // Harmony Memory size (number of stored solutions)
	hsoEliteBias        = 0.25  // probability of biasing toward best known solution
	hsoArrivalDist      = 3.0   // distance threshold for considering bot arrived at target
	hsoBWDecayTicks     = 2500  // ticks over which bandwidth decays from max to min
	hsoSpeedMult        = 5.0   // movement speed multiplier over SwarmBotSpeed
	hsoDivCheckInterval = 200   // ticks between HM diversity checks
	hsoDivThreshold     = 30.0  // minimum RMS spread in HM before diversity injection
	hsoDivInjectFrac    = 0.2   // fraction of HM entries to replace with random when too clustered
)

// HSOHarmony stores one solution in the Harmony Memory.
type HSOHarmony struct {
	X, Y    float64
	Fitness float64
}

// HSOState holds Harmony Search state for the swarm.
type HSOState struct {
	// Harmony Memory — archive of best solutions found so far.
	HM []HSOHarmony

	// Per-bot target position generated by the improvisation process.
	TargetX []float64
	TargetY []float64
	Phase   []int // 0=improvising (moving to new target), 1=arrived (evaluating)

	// Per-bot fitness values (used for avgFitnessVals reporting).
	Fitness []float64

	// Global tracking.
	BestIdx int     // index of best harmony in HM
	BestF   float64 // best fitness found
	BestX   float64 // best position
	BestY   float64

	// HMRevalidated is set after the first TickHSO re-evaluates all HM
	// entries with the current fitness landscape. This is needed because
	// InitHSO runs before the benchmark sets the correct landscape, so HM
	// entries may be seeded with wrong fitness values.
	HMRevalidated bool
}

// InitHSO allocates Harmony Search state and fills the Harmony Memory
// with uniformly distributed positions across the arena. This ensures
// good initial coverage regardless of current bot positions (which may
// be clustered from a previous algorithm run).
func InitHSO(ss *SwarmState) {
	n := len(ss.Bots)
	st := &HSOState{
		HM:      make([]HSOHarmony, 0, hsoHMSize),
		TargetX: make([]float64, n),
		TargetY: make([]float64, n),
		Phase:   make([]int, n),
		Fitness: make([]float64, n),
		BestF:   -1e9,
		BestIdx: -1,
	}

	margin := SwarmEdgeMargin

	// Seed the Harmony Memory with a uniform grid across the arena.
	// Generate more candidates than hsoHMSize, evaluate each, and keep
	// the top hsoHMSize positions. This gives the algorithm a head start
	// on multi-modal landscapes like Gaussian Peaks.
	gridSide := 10 // 10x10 = 100 candidate positions
	candidates := make([]HSOHarmony, 0, gridSide*gridSide)
	usableW := ss.ArenaW - 2*margin
	usableH := ss.ArenaH - 2*margin
	for gx := 0; gx < gridSide; gx++ {
		for gy := 0; gy < gridSide; gy++ {
			x := margin + usableW*(float64(gx)+0.5)/float64(gridSide)
			y := margin + usableH*(float64(gy)+0.5)/float64(gridSide)
			// Add small jitter to avoid exact grid patterns.
			x += (ss.Rng.Float64()*2.0 - 1.0) * usableW * 0.03
			y += (ss.Rng.Float64()*2.0 - 1.0) * usableH * 0.03
			x = math.Max(margin, math.Min(ss.ArenaW-margin, x))
			y = math.Max(margin, math.Min(ss.ArenaH-margin, y))
			f := distanceFitnessPt(ss, x, y)
			candidates = append(candidates, HSOHarmony{X: x, Y: y, Fitness: f})
		}
	}

	// Sort candidates by fitness (descending) and keep top hsoHMSize.
	// Simple selection sort for small array.
	for i := 0; i < len(candidates) && i < hsoHMSize; i++ {
		best := i
		for j := i + 1; j < len(candidates); j++ {
			if candidates[j].Fitness > candidates[best].Fitness {
				best = j
			}
		}
		if best != i {
			candidates[i], candidates[best] = candidates[best], candidates[i]
		}
		st.HM = append(st.HM, candidates[i])
		if candidates[i].Fitness > st.BestF {
			st.BestF = candidates[i].Fitness
			st.BestIdx = i
			st.BestX = candidates[i].X
			st.BestY = candidates[i].Y
		}
	}

	// Assign initial targets: send each bot to a diverse HM position.
	for i := 0; i < n; i++ {
		hmIdx := i % len(st.HM)
		st.TargetX[i] = st.HM[hmIdx].X
		st.TargetY[i] = st.HM[hmIdx].Y
	}

	ss.HSO = st
	ss.HSOOn = true
}

// ClearHSO frees Harmony Search state.
func ClearHSO(ss *SwarmState) {
	ss.HSO = nil
	ss.HSOOn = false
}

// TickHSO runs one tick of the Harmony Search algorithm.
//
// For each bot that has arrived at its target (Phase==1), a new harmony is
// improvised using the standard HSO operators:
//   1. With probability HMCR, pick a note from a random HM entry; otherwise
//      generate a uniformly random position.
//   2. With probability PAR, apply pitch adjustment: perturb the selected
//      note by a random amount within bandwidth BW.
//   3. Evaluate the new harmony and replace the worst HM entry if better.
//   4. Assign the new harmony as the bot's next target.
//
// Bots that have not yet arrived continue steering toward their target.
func TickHSO(ss *SwarmState) {
	if ss.HSO == nil {
		return
	}
	st := ss.HSO
	n := len(ss.Bots)

	// Re-evaluate HM fitness on first tick. InitHSO seeds the HM before
	// the benchmark sets the correct fitness landscape, so HM entries may
	// have fitness values from a different landscape (typically Gaussian).
	if !st.HMRevalidated {
		st.HMRevalidated = true
		st.BestF = -1e9
		for j := range st.HM {
			st.HM[j].Fitness = distanceFitnessPt(ss, st.HM[j].X, st.HM[j].Y)
			if st.HM[j].Fitness > st.BestF {
				st.BestF = st.HM[j].Fitness
				st.BestX = st.HM[j].X
				st.BestY = st.HM[j].Y
			}
		}
	}

	// Grow slices if bots were added.
	for len(st.TargetX) < n {
		st.TargetX = append(st.TargetX, ss.Bots[len(st.TargetX)].X)
		st.TargetY = append(st.TargetY, ss.Bots[len(st.TargetY)].Y)
		st.Phase = append(st.Phase, 0)
		st.Fitness = append(st.Fitness, 0)
	}

	margin := SwarmEdgeMargin

	// Adaptive bandwidth: decreases linearly from max to min over time.
	progress := float64(ss.Tick) / hsoBWDecayTicks
	if progress > 1.0 {
		progress = 1.0
	}
	bw := hsoBWMax - progress*(hsoBWMax-hsoBWMin)

	for i := 0; i < n; i++ {
		bot := &ss.Bots[i]

		// Check if bot arrived at target.
		dx := st.TargetX[i] - bot.X
		dy := st.TargetY[i] - bot.Y
		dist := math.Sqrt(dx*dx + dy*dy)
		if dist < hsoArrivalDist {
			st.Phase[i] = 1
		}

		if st.Phase[i] != 1 {
			continue
		}

		// ── Improvise a new harmony ──

		var newX, newY float64

		if len(st.HM) > 0 && ss.Rng.Float64() < hsoHMCR {
			// Elite bias: with increasing probability, start from the best HM
			// entry instead of a random one. Increases from 25% to 50% over time.
			var hmIdx int
			eliteBias := hsoEliteBias + 0.25*progress
			if ss.Rng.Float64() < eliteBias {
				hmIdx = st.BestIdx
			} else {
				// Tournament selection: pick best of 3 random HM entries
				// for better exploitation than uniform random.
				hmIdx = ss.Rng.Intn(len(st.HM))
				for t := 0; t < 2; t++ {
					cand := ss.Rng.Intn(len(st.HM))
					if st.HM[cand].Fitness > st.HM[hmIdx].Fitness {
						hmIdx = cand
					}
				}
			}
			newX = st.HM[hmIdx].X
			newY = st.HM[hmIdx].Y

			// Pitch adjustment: perturb within adaptive bandwidth.
			if ss.Rng.Float64() < hsoPAR {
				newX += (ss.Rng.Float64()*2.0 - 1.0) * bw
				newY += (ss.Rng.Float64()*2.0 - 1.0) * bw
			}
		} else {
			// Random selection: uniformly random position in arena.
			newX = margin + ss.Rng.Float64()*(ss.ArenaW-2*margin)
			newY = margin + ss.Rng.Float64()*(ss.ArenaH-2*margin)
		}

		// Adaptive global-best attraction: pull new harmonies toward the
		// best known position. Weight increases from 10% to 45% over time.
		if st.BestF > -1e8 {
			gbWeight := 0.10 + 0.35*progress
			newX += gbWeight * (st.BestX - newX)
			newY += gbWeight * (st.BestY - newY)
		}

		// Clamp to arena.
		newX = math.Max(margin, math.Min(ss.ArenaW-margin, newX))
		newY = math.Max(margin, math.Min(ss.ArenaH-margin, newY))

		// Evaluate the new harmony at the target position.
		newF := distanceFitnessPt(ss, newX, newY)

		// Replace worst harmony in HM if the new one is better.
		if len(st.HM) < hsoHMSize {
			st.HM = append(st.HM, HSOHarmony{X: newX, Y: newY, Fitness: newF})
		} else {
			worstIdx := 0
			worstF := st.HM[0].Fitness
			for j := 1; j < len(st.HM); j++ {
				if st.HM[j].Fitness < worstF {
					worstF = st.HM[j].Fitness
					worstIdx = j
				}
			}
			if newF > worstF {
				st.HM[worstIdx] = HSOHarmony{X: newX, Y: newY, Fitness: newF}
			}
		}

		// Update global best.
		if newF > st.BestF {
			st.BestF = newF
			st.BestX = newX
			st.BestY = newY
		}

		// Assign new target and reset phase.
		st.TargetX[i] = newX
		st.TargetY[i] = newY
		st.Phase[i] = 0
	}

	// HM diversity maintenance: if all HM entries cluster tightly,
	// reinject random positions to prevent premature convergence.
	if ss.Tick > 0 && ss.Tick%hsoDivCheckInterval == 0 && len(st.HM) >= 4 {
		// Compute HM centroid and RMS spread.
		var cx, cy float64
		for j := range st.HM {
			cx += st.HM[j].X
			cy += st.HM[j].Y
		}
		cx /= float64(len(st.HM))
		cy /= float64(len(st.HM))
		var sumSq float64
		for j := range st.HM {
			ddx := st.HM[j].X - cx
			ddy := st.HM[j].Y - cy
			sumSq += ddx*ddx + ddy*ddy
		}
		rms := math.Sqrt(sumSq / float64(len(st.HM)))
		if rms < hsoDivThreshold {
			// Replace worst fraction of HM with random positions.
			nReplace := int(float64(len(st.HM)) * hsoDivInjectFrac)
			if nReplace < 1 {
				nReplace = 1
			}
			for r := 0; r < nReplace; r++ {
				// Find worst HM entry.
				worstIdx := 0
				worstF := st.HM[0].Fitness
				for j := 1; j < len(st.HM); j++ {
					if st.HM[j].Fitness < worstF {
						worstF = st.HM[j].Fitness
						worstIdx = j
					}
				}
				rx := margin + ss.Rng.Float64()*(ss.ArenaW-2*margin)
				ry := margin + ss.Rng.Float64()*(ss.ArenaH-2*margin)
				rf := distanceFitnessPt(ss, rx, ry)
				st.HM[worstIdx] = HSOHarmony{X: rx, Y: ry, Fitness: rf}
				if rf > st.BestF {
					st.BestF = rf
					st.BestX = rx
					st.BestY = ry
				}
			}
		}
	}

	// Find best HM index for display.
	st.BestIdx = 0
	for j := 1; j < len(st.HM); j++ {
		if st.HM[j].Fitness > st.HM[st.BestIdx].Fitness {
			st.BestIdx = j
		}
	}

	// Update sensor cache and per-bot fitness for all bots.
	for i := range ss.Bots {
		f := hsoFitness(&ss.Bots[i], ss)
		if i < len(st.Fitness) {
			st.Fitness[i] = f
		}
		ss.Bots[i].HSOFitness = int(f * 100)
		if i < len(st.Phase) {
			ss.Bots[i].HSOPhase = st.Phase[i]
		}
		bdx := st.BestX - ss.Bots[i].X
		bdy := st.BestY - ss.Bots[i].Y
		ss.Bots[i].HSOBestDist = int(math.Sqrt(bdx*bdx + bdy*bdy))
	}
}

// ApplyHSO moves a bot toward its improvised target position via direct
// position updates (required for headless benchmark mode where
// applySwarmPhysics is not called).
//
// Bots in phase 0 (improvising) move toward the target.
// Bots in phase 1 (arrived) wait while the next harmony is generated.
// LED color encodes fitness: cyan gradient from dim (low fitness) to bright.
func ApplyHSO(bot *SwarmBot, ss *SwarmState, idx int) {
	if ss.HSO == nil {
		bot.Speed = SwarmBotSpeed
		return
	}
	st := ss.HSO
	if idx >= len(st.TargetX) {
		bot.Speed = SwarmBotSpeed
		return
	}

	dx := st.TargetX[idx] - bot.X
	dy := st.TargetY[idx] - bot.Y
	dist := math.Sqrt(dx*dx + dy*dy)

	if st.Phase[idx] == 1 {
		// Arrived — idle while evaluating.
		bot.Speed = 0
	} else {
		// Move directly toward target via position update.
		stepSize := SwarmBotSpeed * hsoSpeedMult
		if dist < stepSize {
			// Snap to target for precise fitness evaluation.
			bot.X = st.TargetX[idx]
			bot.Y = st.TargetY[idx]
		} else {
			ratio := stepSize / dist
			bot.X += dx * ratio
			bot.Y += dy * ratio
		}
		bot.Angle = math.Atan2(dy, dx)
		bot.Speed = 0 // prevent double movement in GUI mode

		// Clamp to arena.
		margin := SwarmEdgeMargin
		bot.X = math.Max(margin, math.Min(ss.ArenaW-margin, bot.X))
		bot.Y = math.Max(margin, math.Min(ss.ArenaH-margin, bot.Y))
	}

	// LED: cyan gradient — brighter cyan indicates higher fitness.
	f := hsoFitness(bot, ss)
	fit01 := math.Min(math.Max((f+50)/150, 0), 1)
	g := uint8(80 + fit01*175)
	b := uint8(120 + fit01*135)
	bot.LEDColor = [3]uint8{0, g, b}
}

// hsoFitness evaluates a bot's position fitness using the shared Gaussian
// fitness landscape for consistent comparison across algorithms.
func hsoFitness(bot *SwarmBot, ss *SwarmState) float64 {
	return distanceFitness(bot, ss)
}
