package swarm

import "math"

// Harmony Search Optimization (HSO): A music-inspired metaheuristic algorithm
// that mimics the process of musicians improvising harmonies. Each musician
// (decision variable) plays a note (value) that together form a harmony
// (solution vector). The algorithm maintains a Harmony Memory (HM) of
// previously played good harmonies and generates new ones by:
//
//   Memory consideration — pick a note from the HM with probability HMCR
//   Pitch adjustment    — slightly perturb the selected note with probability PAR
//   Random selection    — choose a completely random note otherwise
//
// The new harmony replaces the worst in HM if it is better, maintaining a
// fixed-size archive of elite solutions. The simplicity and few parameters
// make HSO attractive for continuous and combinatorial optimization alike.
//
// In this 2-D swarm simulation each bot represents a harmony whose "notes"
// are its (X, Y) position. The fitness is proximity to the light source (or
// arena center). Bots steer toward target positions drawn from the HM,
// producing a visually distinct convergence pattern: an initial exploratory
// scatter that gradually coalesces into tight clusters around the optimum.
//
// Reference: Geem, Z.W., Kim, J.H., Loganathan, G.V. (2001)
//
//	"A New Heuristic Optimization Algorithm: Harmony Search",
//	SIMULATION, 76(2), pp. 60-68.

const (
	hsoSteerRate = 0.12  // max steering change per tick (radians)
	hsoHMCR      = 0.90  // Harmony Memory Considering Rate — probability of picking from HM
	hsoPAR       = 0.30  // Pitch Adjusting Rate — probability of perturbing a HM note
	hsoBW        = 40.0  // bandwidth — maximum pitch adjustment distance (pixels)
	hsoHMSize    = 20    // Harmony Memory size (number of stored solutions)
)

// HSOHarmony stores one solution in the Harmony Memory.
type HSOHarmony struct {
	X, Y    float64
	Fitness float64
}

// HSOState holds Harmony Search state for the swarm.
type HSOState struct {
	// Harmony Memory — archive of best solutions found so far.
	HM []HSOHarmony

	// Per-bot target position generated by the improvisation process.
	TargetX []float64
	TargetY []float64
	Phase   []int // 0=improvising (moving to new target), 1=arrived (evaluating)

	// Per-bot fitness values (used for avgFitnessVals reporting).
	Fitness []float64

	// Global tracking.
	BestIdx int     // index of best harmony in HM
	BestF   float64 // best fitness found
	BestX   float64 // best position
	BestY   float64
}

// InitHSO allocates Harmony Search state and fills the Harmony Memory
// with the current bot positions as initial harmonies.
func InitHSO(ss *SwarmState) {
	n := len(ss.Bots)
	st := &HSOState{
		HM:      make([]HSOHarmony, 0, hsoHMSize),
		TargetX: make([]float64, n),
		TargetY: make([]float64, n),
		Phase:   make([]int, n),
		Fitness: make([]float64, n),
		BestF:   -1e9,
		BestIdx: -1,
	}

	// Seed the Harmony Memory with up to hsoHMSize bot positions.
	limit := n
	if limit > hsoHMSize {
		limit = hsoHMSize
	}
	for i := 0; i < limit; i++ {
		f := hsoFitness(&ss.Bots[i], ss)
		st.HM = append(st.HM, HSOHarmony{
			X: ss.Bots[i].X, Y: ss.Bots[i].Y, Fitness: f,
		})
		if f > st.BestF {
			st.BestF = f
			st.BestIdx = i
			st.BestX = ss.Bots[i].X
			st.BestY = ss.Bots[i].Y
		}
	}

	// Assign initial targets (each bot moves to its own position initially).
	for i := 0; i < n; i++ {
		st.TargetX[i] = ss.Bots[i].X
		st.TargetY[i] = ss.Bots[i].Y
	}

	ss.HSO = st
	ss.HSOOn = true
}

// ClearHSO frees Harmony Search state.
func ClearHSO(ss *SwarmState) {
	ss.HSO = nil
	ss.HSOOn = false
}

// TickHSO runs one tick of the Harmony Search algorithm.
//
// For each bot that has arrived at its target (Phase==1), a new harmony is
// improvised using the standard HSO operators:
//   1. With probability HMCR, pick a note from a random HM entry; otherwise
//      generate a uniformly random position.
//   2. With probability PAR, apply pitch adjustment: perturb the selected
//      note by a random amount within bandwidth BW.
//   3. Evaluate the new harmony and replace the worst HM entry if better.
//   4. Assign the new harmony as the bot's next target.
//
// Bots that have not yet arrived continue steering toward their target.
func TickHSO(ss *SwarmState) {
	if ss.HSO == nil {
		return
	}
	st := ss.HSO
	n := len(ss.Bots)

	// Grow slices if bots were added.
	for len(st.TargetX) < n {
		st.TargetX = append(st.TargetX, ss.Bots[len(st.TargetX)].X)
		st.TargetY = append(st.TargetY, ss.Bots[len(st.TargetY)].Y)
		st.Phase = append(st.Phase, 0)
		st.Fitness = append(st.Fitness, 0)
	}

	margin := SwarmEdgeMargin

	for i := 0; i < n; i++ {
		bot := &ss.Bots[i]

		// Check if bot arrived at target.
		dx := st.TargetX[i] - bot.X
		dy := st.TargetY[i] - bot.Y
		dist := math.Sqrt(dx*dx + dy*dy)
		if dist < 15.0 {
			st.Phase[i] = 1
		}

		if st.Phase[i] != 1 {
			continue
		}

		// ── Improvise a new harmony ──

		var newX, newY float64

		if len(st.HM) > 0 && ss.Rng.Float64() < hsoHMCR {
			// Memory consideration: pick a random harmony from HM.
			hmIdx := ss.Rng.Intn(len(st.HM))
			newX = st.HM[hmIdx].X
			newY = st.HM[hmIdx].Y

			// Pitch adjustment: perturb within bandwidth.
			if ss.Rng.Float64() < hsoPAR {
				newX += (ss.Rng.Float64()*2.0 - 1.0) * hsoBW
				newY += (ss.Rng.Float64()*2.0 - 1.0) * hsoBW
			}
		} else {
			// Random selection: uniformly random position in arena.
			newX = margin + ss.Rng.Float64()*(ss.ArenaW-2*margin)
			newY = margin + ss.Rng.Float64()*(ss.ArenaH-2*margin)
		}

		// Clamp to arena.
		newX = math.Max(margin, math.Min(ss.ArenaW-margin, newX))
		newY = math.Max(margin, math.Min(ss.ArenaH-margin, newY))

		// Evaluate the new harmony.
		// Temporarily use bot position to compute fitness at the target.
		origX, origY := bot.X, bot.Y
		bot.X, bot.Y = newX, newY
		newF := hsoFitness(bot, ss)
		bot.X, bot.Y = origX, origY

		// Replace worst harmony in HM if the new one is better.
		if len(st.HM) < hsoHMSize {
			st.HM = append(st.HM, HSOHarmony{X: newX, Y: newY, Fitness: newF})
		} else {
			worstIdx := 0
			worstF := st.HM[0].Fitness
			for j := 1; j < len(st.HM); j++ {
				if st.HM[j].Fitness < worstF {
					worstF = st.HM[j].Fitness
					worstIdx = j
				}
			}
			if newF > worstF {
				st.HM[worstIdx] = HSOHarmony{X: newX, Y: newY, Fitness: newF}
			}
		}

		// Update global best.
		if newF > st.BestF {
			st.BestF = newF
			st.BestX = newX
			st.BestY = newY
		}

		// Assign new target and reset phase.
		st.TargetX[i] = newX
		st.TargetY[i] = newY
		st.Phase[i] = 0
	}

	// Find best HM index for display.
	st.BestIdx = 0
	for j := 1; j < len(st.HM); j++ {
		if st.HM[j].Fitness > st.HM[st.BestIdx].Fitness {
			st.BestIdx = j
		}
	}

	// Update sensor cache and per-bot fitness for all bots.
	for i := range ss.Bots {
		f := hsoFitness(&ss.Bots[i], ss)
		if i < len(st.Fitness) {
			st.Fitness[i] = f
		}
		ss.Bots[i].HSOFitness = int(f * 100)
		if i < len(st.Phase) {
			ss.Bots[i].HSOPhase = st.Phase[i]
		}
		dx := st.BestX - ss.Bots[i].X
		dy := st.BestY - ss.Bots[i].Y
		ss.Bots[i].HSOBestDist = int(math.Sqrt(dx*dx + dy*dy))
	}
}

// ApplyHSO steers a bot toward its improvised target position.
//
// Bots in phase 0 (improvising) steer toward the target at normal speed.
// Bots in phase 1 (arrived) slow down while the next harmony is generated.
// LED color encodes fitness: cyan gradient from dim (low fitness) to bright.
func ApplyHSO(bot *SwarmBot, ss *SwarmState, idx int) {
	if ss.HSO == nil {
		bot.Speed = SwarmBotSpeed
		return
	}
	st := ss.HSO
	if idx >= len(st.TargetX) {
		bot.Speed = SwarmBotSpeed
		return
	}

	dx := st.TargetX[idx] - bot.X
	dy := st.TargetY[idx] - bot.Y
	dist := math.Sqrt(dx*dx + dy*dy)

	if st.Phase[idx] == 1 {
		// Arrived — slow movement while evaluating.
		bot.Speed = SwarmBotSpeed * 0.3
	} else if dist < 30.0 {
		// Approaching target — slow down.
		bot.Speed = SwarmBotSpeed * 0.6
	} else {
		// Heading toward target.
		desired := math.Atan2(dy, dx)
		steerToward(bot, desired, hsoSteerRate)
		bot.Speed = SwarmBotSpeed
	}

	// LED: cyan gradient — brighter cyan indicates higher fitness.
	f := hsoFitness(bot, ss)
	fit01 := math.Min(math.Max((f+50)/150, 0), 1)
	g := uint8(80 + fit01*175)
	b := uint8(120 + fit01*135)
	bot.LEDColor = [3]uint8{0, g, b}
}

// hsoFitness evaluates a bot's position fitness using the shared Gaussian
// fitness landscape for consistent comparison across algorithms.
func hsoFitness(bot *SwarmBot, ss *SwarmState) float64 {
	return distanceFitness(bot, ss)
}
