package swarm

import (
	"math"
	"sort"
)

// Particle Swarm Optimization (PSO): Bots act as particles searching for
// an optimum on a fitness landscape. Each bot remembers its personal best
// position and is attracted toward both its own best and the global best.
// Classic Kennedy & Eberhart (1995) algorithm visualized as swarm behavior.

const (
	psoInertia    = 0.7   // velocity damping (momentum)
	psoCognitive  = 1.5   // attraction toward personal best
	psoSocial     = 2.0   // attraction toward global best
	psoMaxVel     = 7.5   // max velocity component (was 3.0)
	psoUpdateRate = 1     // ticks between fitness evaluations (was 5)

	psoGridRescanRate = 400 // periodic grid rescan every N ticks
	psoGridRescanSize = 14  // grid resolution for periodic rescan (14×14 = 196 samples)
	psoGridInjectTop  = AlgoGridInjectTop // number of top grid points to inject into worst particles
)

// PSOState holds per-bot PSO optimization state.
type PSOState struct {
	VelX      []float64 // velocity X
	VelY      []float64 // velocity Y
	BestX     []float64 // personal best position X
	BestY     []float64 // personal best position Y
	BestFit   []float64 // personal best fitness
	GlobalX   float64   // global best X
	GlobalY   float64   // global best Y
	GlobalFit float64   // global best fitness
	// Fitness landscape: sum of Gaussian peaks
	PeakX []float64
	PeakY []float64
	PeakH []float64 // height (strength)
	PeakS []float64 // sigma (spread)
}

// InitPSO allocates PSO state using the shared Gaussian fitness landscape.
// The shared landscape is generated by initFitnessLandscape (called before
// any algorithm-specific init) and stored in SwarmAlgorithmState. PSO copies
// the peak pointers into PSOState for backward compatibility with the
// existing PSO overlay and sensor code.
func InitPSO(ss *SwarmState) {
	n := len(ss.Bots)
	st := &PSOState{
		VelX:    make([]float64, n),
		VelY:    make([]float64, n),
		BestX:   make([]float64, n),
		BestY:   make([]float64, n),
		BestFit: make([]float64, n),
	}

	// Use shared fitness landscape peaks (already initialised).
	sa := ss.SwarmAlgo
	if sa != nil && len(sa.FitPeakX) > 0 {
		st.PeakX = sa.FitPeakX
		st.PeakY = sa.FitPeakY
		st.PeakH = sa.FitPeakH
		st.PeakS = sa.FitPeakS
	} else {
		// Fallback: generate peaks directly (should not happen with new init order).
		numPeaks := 3 + ss.Rng.Intn(3)
		st.PeakX = make([]float64, numPeaks)
		st.PeakY = make([]float64, numPeaks)
		st.PeakH = make([]float64, numPeaks)
		st.PeakS = make([]float64, numPeaks)
		for p := 0; p < numPeaks; p++ {
			st.PeakX[p] = ss.ArenaW*0.1 + ss.Rng.Float64()*ss.ArenaW*0.8
			st.PeakY[p] = ss.ArenaH*0.1 + ss.Rng.Float64()*ss.ArenaH*0.8
			st.PeakH[p] = 50 + ss.Rng.Float64()*50
			st.PeakS[p] = 40 + ss.Rng.Float64()*80
		}
	}

	// Initialize personal bests
	st.GlobalFit = -1
	for i := range ss.Bots {
		st.BestX[i] = ss.Bots[i].X
		st.BestY[i] = ss.Bots[i].Y
		f := distanceFitness(&ss.Bots[i], ss)
		st.BestFit[i] = f
		if f > st.GlobalFit {
			st.GlobalFit = f
			st.GlobalX = ss.Bots[i].X
			st.GlobalY = ss.Bots[i].Y
		}
	}

	ss.PSO = st
	ss.PSOOn = true
}

// ClearPSO frees PSO state.
func ClearPSO(ss *SwarmState) {
	ss.PSO = nil
	ss.PSOOn = false
}

// psoEvaluate computes the fitness at a given position.
func psoEvaluate(st *PSOState, x, y float64) float64 {
	fit := 0.0
	for p := range st.PeakX {
		dx := x - st.PeakX[p]
		dy := y - st.PeakY[p]
		fit += st.PeakH[p] * math.Exp(-(dx*dx+dy*dy)/(2*st.PeakS[p]*st.PeakS[p]))
	}
	return fit
}

// TickPSO updates PSO velocities, evaluates fitness, updates bests.
func TickPSO(ss *SwarmState) {
	if ss.PSO == nil || ss.Rng == nil {
		return
	}
	st := ss.PSO
	n := len(ss.Bots)

	// Grow slices if bots added
	for len(st.VelX) < n {
		st.VelX = append(st.VelX, 0)
		st.VelY = append(st.VelY, 0)
		st.BestX = append(st.BestX, ss.Bots[len(st.BestX)].X)
		st.BestY = append(st.BestY, ss.Bots[len(st.BestY)].Y)
		st.BestFit = append(st.BestFit, 0)
	}

	// Periodic grid rescan: systematically sample the arena to find the
	// global optimum on deceptive landscapes like Schwefel.
	if ss.Tick > 0 && ss.Tick%psoGridRescanRate == 0 && n > 0 {
		psoGridRescan(ss, st)
	}

	evaluate := ss.Tick%psoUpdateRate == 0

	for i := range ss.Bots {
		bot := &ss.Bots[i]

		if evaluate {
			f := distanceFitness(bot, ss)
			if f > st.BestFit[i] {
				st.BestFit[i] = f
				st.BestX[i] = bot.X
				st.BestY[i] = bot.Y
			}
			if f > st.GlobalFit {
				st.GlobalFit = f
				st.GlobalX = bot.X
				st.GlobalY = bot.Y
			}
		}

		// PSO velocity update
		r1 := ss.Rng.Float64()
		r2 := ss.Rng.Float64()
		st.VelX[i] = psoInertia*st.VelX[i] +
			psoCognitive*r1*(st.BestX[i]-bot.X) +
			psoSocial*r2*(st.GlobalX-bot.X)
		st.VelY[i] = psoInertia*st.VelY[i] +
			psoCognitive*r1*(st.BestY[i]-bot.Y) +
			psoSocial*r2*(st.GlobalY-bot.Y)

		// Clamp velocity
		if st.VelX[i] > psoMaxVel {
			st.VelX[i] = psoMaxVel
		} else if st.VelX[i] < -psoMaxVel {
			st.VelX[i] = -psoMaxVel
		}
		if st.VelY[i] > psoMaxVel {
			st.VelY[i] = psoMaxVel
		} else if st.VelY[i] < -psoMaxVel {
			st.VelY[i] = -psoMaxVel
		}

		// Update sensor cache
		currentFit := distanceFitness(bot, ss)
		bot.PSOFitness = int(currentFit)
		bot.PSOBest = int(st.BestFit[i])

		// Distance to global best
		dx := st.GlobalX - bot.X
		dy := st.GlobalY - bot.Y
		bot.PSOGlobalDist = int(math.Min(9999, math.Sqrt(dx*dx+dy*dy)))
	}
}

// psoGridRescan evaluates a grid of points across the arena and teleports
// the worst particles to the best-discovered grid positions. This is
// critical for Schwefel where the global optimum is far from local optima.
func psoGridRescan(ss *SwarmState, st *PSOState) {
	margin := 10.0
	usableW := ss.ArenaW - 2*margin
	usableH := ss.ArenaH - 2*margin
	n := len(ss.Bots)

	gridPts := make([]gridPt, 0, psoGridRescanSize*psoGridRescanSize)
	for gx := 0; gx < psoGridRescanSize; gx++ {
		for gy := 0; gy < psoGridRescanSize; gy++ {
			x := margin + usableW*(float64(gx)+0.5)/float64(psoGridRescanSize)
			y := margin + usableH*(float64(gy)+0.5)/float64(psoGridRescanSize)
			// Small jitter
			x += (ss.Rng.Float64()*2.0 - 1.0) * usableW * 0.02
			y += (ss.Rng.Float64()*2.0 - 1.0) * usableH * 0.02
			f := distanceFitnessPt(ss, x, y)
			gridPts = append(gridPts, gridPt{x, y, f})
			// Update global best from grid
			if f > st.GlobalFit {
				st.GlobalFit = f
				st.GlobalX = x
				st.GlobalY = y
			}
		}
	}

	// Sort grid points by fitness descending
	sort.Slice(gridPts, func(i, j int) bool { return gridPts[i].f > gridPts[j].f })

	// Find worst particles by personal best fitness
	worst := make([]idxFit, n)
	for i := 0; i < n; i++ {
		worst[i] = idxFit{i, st.BestFit[i]}
	}
	sort.Slice(worst, func(i, j int) bool { return worst[i].f < worst[j].f })

	// Inject top grid points into worst particles
	injectCount := psoGridInjectTop
	if injectCount > n {
		injectCount = n
	}
	if injectCount > len(gridPts) {
		injectCount = len(gridPts)
	}
	for k := 0; k < injectCount; k++ {
		bi := worst[k].idx
		gp := gridPts[k]
		jx := (ss.Rng.Float64()*2 - 1) * 5
		jy := (ss.Rng.Float64()*2 - 1) * 5
		ss.Bots[bi].X = gp.x + jx
		ss.Bots[bi].Y = gp.y + jy
		// Reset velocity
		st.VelX[bi] = 0
		st.VelY[bi] = 0
		// Update personal best if grid position is better
		if gp.f > st.BestFit[bi] {
			st.BestFit[bi] = gp.f
			st.BestX[bi] = gp.x
			st.BestY[bi] = gp.y
		}
	}
}

// ApplyPSOMove applies PSO velocity to bot movement via direct position
// updates (eigenbewegung). Bots move directly by their velocity vector
// so they converge in both GUI and benchmark mode. Speed is set to 0
// afterward to prevent double-movement in GUI mode.
func ApplyPSOMove(bot *SwarmBot, ss *SwarmState, idx int) {
	if ss.PSO == nil || idx >= len(ss.PSO.VelX) {
		bot.Speed = 0
		return
	}
	st := ss.PSO

	// Apply velocity directly to position (eigenbewegung)
	vx, vy := st.VelX[idx], st.VelY[idx]
	speed := math.Sqrt(vx*vx + vy*vy)
	if speed > 0.1 {
		bot.X += vx
		bot.Y += vy
		bot.Angle = math.Atan2(vy, vx)
	}

	// Clamp to arena
	if bot.X < SwarmBotRadius {
		bot.X = SwarmBotRadius
	}
	if bot.X > ss.ArenaW-SwarmBotRadius {
		bot.X = ss.ArenaW - SwarmBotRadius
	}
	if bot.Y < SwarmBotRadius {
		bot.Y = SwarmBotRadius
	}
	if bot.Y > ss.ArenaH-SwarmBotRadius {
		bot.Y = ss.ArenaH - SwarmBotRadius
	}
	bot.Speed = 0

	// LED: green = high fitness, red = low fitness
	fit := distanceFitness(bot, ss)
	t := math.Min(1, fit/80.0)
	bot.LEDColor = [3]uint8{uint8((1 - t) * 255), uint8(t * 255), 50}
}
